# AUTOGENERATED! DO NOT EDIT! File to edit: AccidentBcn.ipynb.

# %% auto 0
__all__ = []

# %% AccidentBcn.ipynb 4
from datetime import datetime

import streamlit as st

from sklearn.preprocessing import StandardScaler
from datetime import datetime
import streamlit as st
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score,mean_squared_error
import  pandas as pd
import  numpy as np
import time
import warnings
warnings.filterwarnings('ignore')
import streamlit.components.v1 as components
import base64

# ----- Page configs -----
st.set_page_config(
        page_title = "Fallou Fall Portfolio" ,
        page_icon = "🧪" ,
        )

# ----- Left menu -----
with st.sidebar :
    st.image("eae_img.png" , width = 200)
    st.write(
            """I delved into the extensive dataset of car accidents in Barcelona, Catalonia. Through meticulous analysis, I uncovered temporal and spatial patterns, identified key factors contributing to accidents, and developed predictive models to forecast future occurrences. My findings provided valuable insights for policymakers and urban planners, guiding efforts to enhance traffic safety measures and mitigate risks. Ultimately, the journey exemplified the power of data science in driving positive societal change and fostering safer communities.""")
    st.write(
            "Data extracted from: https://opendata-ajuntament.barcelona.cat/data/es/dataset/accidents_causa_conductor_gu_bcn/resource/5a040155-38b3-4b19-a4b0-c84a0618d363/download/2023_accidents_causa_conductor_gu_bcn_.csv")

# ----- Title of the page -----

st.title("🚖 Catalunya Accidents 2023🚖")

#nrows = st.slider("Select the number of rows to read:", min_value=150, max_value=24000, step=500)
try :
    url = "https://opendata-ajuntament.barcelona.cat/data/es/dataset/accidents_causa_conductor_gu_bcn/resource/5a040155-38b3-4b19-a4b0-c84a0618d363/download/2023_accidents_causa_conductor_gu_bcn_.csv"
    df = pd.read_csv(url ,index_col=False)

except FileNotFoundError :
    st.error("Error: Data file not found. Please check the path.")

st.dataframe(df.head(5))





